#Συνάρτηση για την εμφάνιση στην οθόνη της κρεμάλας και της βαθμολογίας.
#mistakes: ο αριθμός των λάθος απαντήσεων.
#guesses: όλα τα γράμματα που έχουν μαντευτεί.
#DashStr: η συμβολοσειρά με τις παύλες που αντιστοιχούν στα γράμματα της λέξης,
#            που δεν έχουν μαντευτεί ακόμα και τα γράμματα που έχουν μαντευτεί σωστά.
#WordNumber,Score,HighScore: μεταβλητές για την βαθμολογία.
def draw(mistakes,guesses,WordNumber,Score,HighScore,DashStr):
    if mistakes == 0:
        print("  ------")
        print("  |    |")
        print("  |                                          Guesed:",guesses)
        print("  |     ")
        print("  |                                          Word #:",WordNumber)
        print("  |                                          Score:",Score)
        print("  |                                          High Score:",HighScore)
        print("-- -----")
        print("|      |___")
        print("|__________|\n")
        print('Word:', DashStr)
    elif mistakes == 1:
        print("  ------")
        print("  |    |")
        print("  |    0                                     Guesed:",guesses)
        print("  |     ")
        print("  |                                          Word #:",WordNumber)
        print("  |                                          Score:",Score)
        print("  |                                          High Score:",HighScore)
        print("-- -----")
        print("|      |___")
        print("|__________|\n")
        print('Word:', DashStr)
    elif mistakes == 2:
        print("  ------")
        print("  |    |")
        print("  |    0                                     Guesed:",guesses)
        print("  |    | ")
        print("  |                                          Word #:",WordNumber)
        print("  |                                          Score:",Score)
        print("  |                                          High Score:  ",HighScore)
        print("-- -----")
        print("|      |___")
        print("|__________|\n")
        print('Word:', DashStr)
    elif mistakes == 3:
        print("  ------")
        print("  |    |")
        print("  |    0                                     Guesed:",guesses)
        print("  |    | ")
        print("  |    |                                     Word #:",WordNumber)
        print("  |                                          Score:",Score)
        print("  |                                          High Score:  ",HighScore)
        print("-- -----")
        print("|      |___")
        print("|__________|\n")
        print('Word:', DashStr)
    elif mistakes == 4:
        print("  ------")
        print("  |    |")
        print("  |    0                                     Guesed:",guesses)
        print("  |   /|\ ")
        print("  |    |                                     Word #:",WordNumber)
        print("  |                                          Score:",Score)
        print("  |                                          High Score:  ",HighScore)
        print("-- -----")
        print("|      |___")
        print("|__________|\n")
        print('Word:', DashStr)
    elif mistakes == 5:
        print("  ------")
        print("  |    |")
        print("  |    0                                     Guesed:",guesses)
        print("  |   /|\ ")
        print("  |    |                                     Word #:",WordNumber)
        print("  |   / \                                    Score:",Score)
        print("  |                                          High Score:",HighScore)
        print("-- -----")
        print("|      |___")
        print("|__________|\n")
        print('Word:', DashStr)
